import React, { createContext, useContext, useState, useEffect } from "react";

type Lang = "en" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // ── Navigation ────────────────────────────────────────────────────────────
    "nav.dashboard": "Dashboard",
    "nav.incidents": "Incidents",
    "nav.triage": "Triage",
    "nav.tracking": "Patient Tracking",
    "nav.orQueue": "OR Queue",
    "nav.resources": "Resources",
    "nav.transport": "Transport",
    "nav.icsForms": "ICS Forms",
    "nav.emtMds": "EMT MDS",
    "nav.aar": "After-Action Review",
    "nav.comms": "Communications",
    "nav.admin": "Admin",
    "nav.publicPortal": "Public Portal",

    // ── Common UI ─────────────────────────────────────────────────────────────
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.save": "Save",
    "common.saving": "Saving...",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.submit": "Submit",
    "common.submitting": "Submitting...",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.view": "View",
    "common.back": "Back",
    "common.next": "Next",
    "common.yes": "Yes",
    "common.no": "No",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.notes": "Notes",
    "common.date": "Date",
    "common.time": "Time",
    "common.name": "Name",
    "common.type": "Type",
    "common.facility": "Facility",
    "common.total": "Total",
    "common.available": "Available",
    "common.inUse": "In Use",
    "common.noData": "No data available",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.confirm": "Confirm",
    "common.logout": "Sign Out",
    "common.profile": "Profile",
    "common.settings": "Settings",
    "common.refresh": "Refresh",
    "common.add": "Add",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.acknowledge": "Acknowledge",
    "common.send": "Send",
    "common.copy": "Copy",
    "common.revoke": "Revoke",
    "common.resend": "Resend",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.all": "All",
    "common.none": "None",
    "common.unknown": "Unknown",
    "common.pending": "Pending",
    "common.accepted": "Accepted",
    "common.rejected": "Rejected",
    "common.expired": "Expired",
    "common.priority": "Priority",
    "common.duration": "Duration",
    "common.location": "Location",
    "common.description": "Description",
    "common.details": "Details",
    "common.history": "History",
    "common.timeline": "Timeline",
    "common.report": "Report",
    "common.language": "Language",
    "common.english": "English",
    "common.arabic": "Arabic",

    // ── Auth pages ────────────────────────────────────────────────────────────
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.requestAccess": "Request access from your administrator",
    "auth.inviteOnly": "Invite-only access",
    "auth.inviteOnlyDesc": "Use your invitation link to create an account, or sign in if you already have one.",
    "auth.createAccount": "Create Your Account",
    "auth.createAccountBtn": "Create Account & Sign In",
    "auth.creatingAccount": "Creating account...",
    "auth.invitedBy": "Invited by",
    "auth.resetPassword": "Reset Password",
    "auth.sendResetLink": "Send Reset Link",
    "auth.sending": "Sending...",
    "auth.setNewPassword": "Set New Password",
    "auth.newPassword": "New Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.currentPassword": "Current Password",
    "auth.changePassword": "Change Password",
    "auth.passwordChanged": "Password changed successfully",
    "auth.resetSuccess": "Password reset successfully. You are now signed in.",
    "auth.checkInbox": "Check your inbox",
    "auth.resetEmailSent": "If an account exists for that email, your administrator will receive a password reset link shortly.",
    "auth.passwordMin": "Password must be at least 8 characters",
    "auth.passwordsNoMatch": "Passwords do not match",
    "auth.passwordReq1": "At least 8 characters",
    "auth.passwordReq2": "Contains a number",
    "auth.passwordReq3": "Contains a letter",
    "auth.backToSignIn": "Back to Sign In",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.demoAccounts": "Demo Accounts",
    "auth.demoPassword": "Password for all accounts",
    "auth.demoAutoFill": "Click any row to auto-fill the form",

    // ── Triage ────────────────────────────────────────────────────────────────
    "triage.IMMEDIATE": "Immediate",
    "triage.DELAYED": "Delayed",
    "triage.MINIMAL": "Minimal",
    "triage.EXPECTANT": "Expectant",
    "triage.DECEASED": "Deceased",
    "triage.UNKNOWN": "Unknown",
    "triage.category": "Triage Category",
    "triage.algorithm": "Algorithm",
    "triage.SALT": "SALT",
    "triage.START": "START",
    "triage.JUMPSTART": "JumpSTART (Pediatric)",
    "triage.registerCasualty": "Register Casualty",
    "triage.startAssessment": "Register & Start SALT Triage",
    "triage.tagSerial": "Tag Serial Number",
    "triage.estimatedAge": "Estimated Age",
    "triage.sex": "Sex",
    "triage.sex.MALE": "Male",
    "triage.sex.FEMALE": "Female",
    "triage.sex.UNKNOWN": "Unknown",
    "triage.nationality": "Nationality",
    "triage.gps": "GPS Coordinates",
    "triage.canWalk": "Can the patient walk to a designated area?",
    "triage.hasLifeThreat": "Does the patient have obvious life-threatening haemorrhage or airway obstruction?",
    "triage.lsiPossible": "Is a lifesaving intervention feasible?",
    "triage.abnormalVitals": "Is the respiratory rate abnormal (< 10 or > 30/min), pulse absent, or does the patient fail to follow commands?",
    "triage.confirmTriage": "Confirm Triage",
    "triage.reassess": "Reassess",
    "triage.noCasualties": "No casualties registered",
    "triage.selectIncident": "Select an incident to view the triage board",
    "triage.identityConfirmed": "ID Confirmed",

    // ── Incidents ─────────────────────────────────────────────────────────────
    "incident.create": "Declare Incident",
    "incident.declare": "Declare New Incident",
    "incident.name": "Incident Name (English)",
    "incident.nameAr": "Incident Name (Arabic)",
    "incident.type": "Type",
    "incident.severity": "Severity",
    "incident.location": "Location Description",
    "incident.estimatedCasualties": "Estimated Casualties",
    "incident.notes": "Notes",
    "incident.activatedAt": "Activated",
    "incident.closedAt": "Closed",
    "incident.status.ACTIVATED": "Activated",
    "incident.status.ESCALATED": "Escalated",
    "incident.status.DEACTIVATED": "Deactivated",
    "incident.status.CLOSED": "Closed",
    "incident.severity.LOW": "Low",
    "incident.severity.MODERATE": "Moderate",
    "incident.severity.HIGH": "High",
    "incident.severity.CATASTROPHIC": "Catastrophic",
    "incident.type.MASS_CASUALTY": "Mass Casualty",
    "incident.type.NATURAL_DISASTER": "Natural Disaster",
    "incident.type.HAZMAT": "HAZMAT",
    "incident.type.TERRORISM": "Terrorism",
    "incident.type.PANDEMIC": "Pandemic",
    "incident.type.INFRASTRUCTURE": "Infrastructure Failure",
    "incident.type.OTHER": "Other",
    "incident.noActive": "No active incidents",
    "incident.allIncidents": "All Incidents",

    // ── Patient Tracking ──────────────────────────────────────────────────────
    "tracking.board": "Patient Tracking Board",
    "tracking.provisionalId": "Provisional ID",
    "tracking.addEvent": "Add Event",
    "tracking.eventType": "Event Type",
    "tracking.locationDesc": "Location Description",
    "tracking.confirmIdentity": "Confirm Identity",
    "tracking.firstName": "First Name",
    "tracking.lastName": "Last Name",
    "tracking.nationalId": "National ID",
    "tracking.disposition": "Disposition",
    "tracking.disposition.AT_SCENE": "At Scene",
    "tracking.disposition.IN_TRANSPORT": "In Transport",
    "tracking.disposition.AT_FACILITY": "At Facility",
    "tracking.disposition.DISCHARGED": "Discharged",
    "tracking.disposition.TRANSFERRED": "Transferred",
    "tracking.disposition.DECEASED": "Deceased",
    "tracking.noEvents": "No events recorded",
    "tracking.noAssessments": "No triage assessments",

    // ── OR Queue ──────────────────────────────────────────────────────────────
    "or.newCase": "New OR Case",
    "or.caseCode": "Case Code",
    "or.procedureType": "Procedure Type",
    "or.priority": "Priority (1-100)",
    "or.estimatedDuration": "Estimated Duration (min)",
    "or.bloodType": "Blood Type",
    "or.isDamageControl": "Damage Control Surgery (DCS)",
    "or.mtpActivated": "MTP Active",
    "or.rbcUnits": "pRBC Units",
    "or.ffpUnits": "FFP Units",
    "or.platelets": "Platelets",
    "or.transition": "Advance Status",
    "or.activeInOR": "Active in OR",
    "or.pendingOR": "Pending",
    "or.completedOR": "Completed",
    "or.status.PROPOSED": "Proposed",
    "or.status.SCHEDULED": "Scheduled",
    "or.status.IN_OR_PREP": "OR Prep",
    "or.status.INDUCTION": "Induction",
    "or.status.INCISION": "Incision",
    "or.status.CLOSURE": "Closure",
    "or.status.IN_PACU": "In PACU",
    "or.status.OUT_PACU": "Out of PACU",
    "or.status.COMPLETE": "Complete",
    "or.status.CANCELLED": "Cancelled",
    "or.status.ABORTED": "Aborted",

    // ── Resources ─────────────────────────────────────────────────────────────
    "resources.title": "Resources & Logistics",
    "resources.addResource": "Add Resource",
    "resources.resourceName": "Resource Name",
    "resources.resourceType": "Resource Type",
    "resources.totalCount": "Total",
    "resources.inUseCount": "In Use",
    "resources.availableCount": "Available",
    "resources.maintenanceCount": "In Maintenance",
    "resources.lowThreshold": "Low Alert Threshold",
    "resources.unit": "Unit",
    "resources.lowAlert": "LOW",
    "resources.utilization": "Utilization",
    "resources.criticalCare": "Critical Care",
    "resources.surgical": "Surgical",
    "resources.bloodProducts": "Blood Products",
    "resources.ppe": "PPE",
    "resources.medications": "Medications",

    // ── Transport ─────────────────────────────────────────────────────────────
    "transport.title": "Transport",
    "transport.addTransport": "Add Transport",
    "transport.transportCode": "Transport Code",
    "transport.vehicleType": "Vehicle Type",
    "transport.driverName": "Driver / Crew",
    "transport.etaMinutes": "ETA (minutes)",
    "transport.status.AVAILABLE": "Available",
    "transport.status.DISPATCHED": "Dispatched",
    "transport.status.EN_ROUTE": "En Route",
    "transport.status.AT_SCENE": "At Scene",
    "transport.status.LOADED": "Loaded",
    "transport.status.RETURNING": "Returning",
    "transport.status.OUT_OF_SERVICE": "Out of Service",
    "transport.noTransports": "No transports registered",

    // ── ICS Forms ─────────────────────────────────────────────────────────────
    "ics.title": "ICS Forms",
    "ics.submitForm": "Submit Form",
    "ics.acknowledge": "Acknowledge",
    "ics.status.DRAFT": "Draft",
    "ics.status.SUBMITTED": "Submitted",
    "ics.status.ACKNOWLEDGED": "Acknowledged",
    "ics.status.SUPERSEDED": "Superseded",
    "ics.HICS_201": "HICS 201 — Incident Briefing",
    "ics.HICS_202": "HICS 202 — Incident Objectives",
    "ics.HICS_203": "HICS 203 — Organisation Assignment",
    "ics.HICS_204": "HICS 204 — Assignment List",
    "ics.HICS_205A": "HICS 205A — Communications List",
    "ics.HICS_213": "HICS 213 — General Message",
    "ics.HICS_214": "HICS 214 — Activity Log",
    "ics.HICS_254": "HICS 254 — Patient Tracking",
    "ics.noForms": "No ICS forms submitted",

    // ── Communications ────────────────────────────────────────────────────────
    "comms.title": "Communications",
    "comms.sendMessage": "Send Message",
    "comms.channel": "Channel",
    "comms.messagePriority": "Priority",
    "comms.priority.ROUTINE": "Routine",
    "comms.priority.URGENT": "Urgent",
    "comms.priority.FLASH": "Flash",
    "comms.channel.COMMAND": "Command",
    "comms.channel.OPERATIONS": "Operations",
    "comms.channel.LOGISTICS": "Logistics",
    "comms.channel.MEDICAL": "Medical",
    "comms.channel.GENERAL": "General",
    "comms.noMessages": "No messages in this channel",
    "comms.acknowledged": "Acknowledged",

    // ── EMT MDS ───────────────────────────────────────────────────────────────
    "emtMds.title": "WHO EMT MDS Reports",
    "emtMds.newReport": "New Report",
    "emtMds.orgName": "Organisation Name",
    "emtMds.classification": "EMT Classification",
    "emtMds.consultations": "Total Consultations",
    "emtMds.admissions": "New Admissions",
    "emtMds.bedCapacity": "Total Bed Capacity",
    "emtMds.traumaCases": "Trauma Cases",
    "emtMds.surgicalProcedures": "Surgical Procedures",
    "emtMds.deaths": "Deaths",
    "emtMds.discharges": "Discharges",
    "emtMds.referrals": "Referrals",
    "emtMds.constraints": "Operational Constraints",
    "emtMds.risks": "Community Risks",
    "emtMds.status.DRAFT": "Draft",
    "emtMds.status.SUBMITTED": "Submitted",
    "emtMds.status.APPROVED": "Approved",
    "emtMds.noReports": "No EMT MDS reports",

    // ── AAR ───────────────────────────────────────────────────────────────────
    "aar.title": "After-Action Review",
    "aar.selectIncident": "Select an incident for AAR",
    "aar.totalCasualties": "Total Casualties",
    "aar.deceased": "Deceased",
    "aar.discharged": "Discharged",
    "aar.mortalityRate": "Mortality Rate",
    "aar.survivalRate": "Survival Rate",
    "aar.orCompleted": "OR Cases Completed",
    "aar.identityConfirmed": "Identity Confirmed",
    "aar.duration": "Incident Duration",
    "aar.ongoing": "Ongoing",
    "aar.kpis": "Standard KPIs",
    "aar.selectPrompt": "Select an incident to view AAR KPIs",
    "aar.closedHint": "Try the CLOSED incident for a complete AAR",

    // ── Admin Panel ───────────────────────────────────────────────────────────
    "admin.title": "Admin Panel",
    "admin.users": "Users",
    "admin.invitations": "Invitations",
    "admin.accessRequests": "Access Requests",
    "admin.facilities": "Facilities",
    "admin.auditLog": "Audit Log",
    "admin.addUser": "Add User",
    "admin.editUser": "Edit User Profile",
    "admin.deleteUser": "Delete User",
    "admin.deleteUserConfirm": "Delete user? This cannot be undone.",
    "admin.setPassword": "Set Password",
    "admin.setPasswordFor": "Set Password for",
    "admin.sendInvitation": "Send Invitation",
    "admin.createInvitation": "Create Invitation",
    "admin.inviteEmail": "Email Address",
    "admin.inviteRole": "Assigned Role",
    "admin.inviteMessage": "Personal Message (optional)",
    "admin.inviteCreated": "Invitation created!",
    "admin.inviteExpiry": "Expires",
    "admin.inviteLink": "Invite Link",
    "admin.invitedBy": "Invited by",
    "admin.addFacility": "Add Facility",
    "admin.facilityName": "Name (English)",
    "admin.facilityNameAr": "Name (Arabic)",
    "admin.facilityCode": "Code",
    "admin.facilityType": "Type",
    "admin.facilityCity": "City",
    "admin.facilityPhone": "Phone",
    "admin.totalBeds": "Total Beds",
    "admin.icuBeds": "ICU Beds",
    "admin.orRooms": "OR Rooms",
    "admin.ventilators": "Ventilators",
    "admin.fullName": "Full Name",
    "admin.email": "Email Address",
    "admin.jobTitle": "Job Title",
    "admin.phone": "Phone",
    "admin.role": "Role",
    "admin.language": "Language",
    "admin.activeAccount": "Active Account",
    "admin.lastSignIn": "Last Sign In",
    "admin.noUsers": "No users found",
    "admin.noInvitations": "No invitations sent yet",
    "admin.noRequests": "No access requests yet",
    "admin.searchUsers": "Search users...",
    "admin.requestFrom": "submitted a request",
    "admin.sendInvite": "Send Invite",
    "admin.reject": "Reject",
    "admin.invited": "Invited",
    "admin.auditUser": "User",
    "admin.auditAction": "Action",
    "admin.auditResource": "Resource",
    "admin.auditIp": "IP Address",
    "admin.noAuditLogs": "No audit log entries",

    // ── Dashboard ─────────────────────────────────────────────────────────────
    "dashboard.title": "Command Dashboard",
    "dashboard.activeIncidents": "Active Incidents",
    "dashboard.totalCasualties": "Total Casualties",
    "dashboard.immediate": "Immediate (Red)",
    "dashboard.orActive": "Active OR Cases",
    "dashboard.orPending": "Pending OR Cases",
    "dashboard.quickNav": "Quick Navigation",
    "dashboard.noActiveIncidents": "No active incidents",

    // ── Roles ─────────────────────────────────────────────────────────────────
    "role.superadmin": "Super Admin",
    "role.admin": "Admin",
    "role.incident_commander": "Incident Commander",
    "role.clinician": "Clinician",
    "role.triage_officer": "Triage Officer",
    "role.logistics": "Logistics",
    "role.viewer": "Viewer",

    // ── Public Portal ─────────────────────────────────────────────────────────
    "portal.title": "Family Reunification Portal",
    "portal.subtitle": "Search for loved ones affected by mass casualty incidents.",
    "portal.search": "Search by Civil ID or Triage Tag",
    "portal.privacyNotice": "This portal displays general status information only. No personal medical data is shared.",
    "portal.noResults": "No match found. Please call emergency services.",
  },

  ar: {
    // ── Navigation ────────────────────────────────────────────────────────────
    "nav.dashboard": "لوحة القيادة",
    "nav.incidents": "الحوادث",
    "nav.triage": "الفرز",
    "nav.tracking": "تتبع المرضى",
    "nav.orQueue": "قائمة انتظار غرفة العمليات",
    "nav.resources": "الموارد",
    "nav.transport": "النقل",
    "nav.icsForms": "نماذج ICS",
    "nav.emtMds": "تقارير EMT MDS",
    "nav.aar": "مراجعة ما بعد الحادث",
    "nav.comms": "الاتصالات",
    "nav.admin": "الإدارة",
    "nav.publicPortal": "البوابة العامة",

    // ── Common UI ─────────────────────────────────────────────────────────────
    "common.loading": "جارٍ التحميل...",
    "common.error": "حدث خطأ",
    "common.save": "حفظ",
    "common.saving": "جارٍ الحفظ...",
    "common.cancel": "إلغاء",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.create": "إنشاء",
    "common.submit": "إرسال",
    "common.submitting": "جارٍ الإرسال...",
    "common.close": "إغلاق",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.export": "تصدير",
    "common.view": "عرض",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.status": "الحالة",
    "common.actions": "الإجراءات",
    "common.notes": "ملاحظات",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.name": "الاسم",
    "common.type": "النوع",
    "common.facility": "المنشأة",
    "common.total": "الإجمالي",
    "common.available": "متاح",
    "common.inUse": "قيد الاستخدام",
    "common.noData": "لا توجد بيانات",
    "common.required": "مطلوب",
    "common.optional": "اختياري",
    "common.confirm": "تأكيد",
    "common.logout": "تسجيل الخروج",
    "common.profile": "الملف الشخصي",
    "common.settings": "الإعدادات",
    "common.refresh": "تحديث",
    "common.add": "إضافة",
    "common.remove": "إزالة",
    "common.update": "تحديث",
    "common.acknowledge": "تأكيد الاستلام",
    "common.send": "إرسال",
    "common.copy": "نسخ",
    "common.revoke": "إلغاء",
    "common.resend": "إعادة الإرسال",
    "common.active": "نشط",
    "common.inactive": "غير نشط",
    "common.all": "الكل",
    "common.none": "لا شيء",
    "common.unknown": "غير معروف",
    "common.pending": "قيد الانتظار",
    "common.accepted": "مقبول",
    "common.rejected": "مرفوض",
    "common.expired": "منتهي الصلاحية",
    "common.priority": "الأولوية",
    "common.duration": "المدة",
    "common.location": "الموقع",
    "common.description": "الوصف",
    "common.details": "التفاصيل",
    "common.history": "السجل",
    "common.timeline": "الجدول الزمني",
    "common.report": "تقرير",
    "common.language": "اللغة",
    "common.english": "English",
    "common.arabic": "العربية",

    // ── Auth pages ────────────────────────────────────────────────────────────
    "auth.signIn": "تسجيل الدخول",
    "auth.signingIn": "جارٍ تسجيل الدخول...",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.forgotPassword": "نسيت كلمة المرور؟",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.requestAccess": "اطلب الوصول من المسؤول",
    "auth.inviteOnly": "وصول بالدعوة فقط",
    "auth.inviteOnlyDesc": "استخدم رابط الدعوة لإنشاء حساب، أو سجّل دخولك إذا كان لديك حساب.",
    "auth.createAccount": "إنشاء حسابك",
    "auth.createAccountBtn": "إنشاء الحساب وتسجيل الدخول",
    "auth.creatingAccount": "جارٍ إنشاء الحساب...",
    "auth.invitedBy": "دعوة من",
    "auth.resetPassword": "إعادة تعيين كلمة المرور",
    "auth.sendResetLink": "إرسال رابط الإعادة",
    "auth.sending": "جارٍ الإرسال...",
    "auth.setNewPassword": "تعيين كلمة مرور جديدة",
    "auth.newPassword": "كلمة المرور الجديدة",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.currentPassword": "كلمة المرور الحالية",
    "auth.changePassword": "تغيير كلمة المرور",
    "auth.passwordChanged": "تم تغيير كلمة المرور بنجاح",
    "auth.resetSuccess": "تم إعادة تعيين كلمة المرور. أنت الآن مسجّل الدخول.",
    "auth.checkInbox": "تحقق من بريدك الوارد",
    "auth.resetEmailSent": "إذا كان الحساب موجوداً، سيتلقى المسؤول رابط إعادة التعيين قريباً.",
    "auth.passwordMin": "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
    "auth.passwordsNoMatch": "كلمتا المرور غير متطابقتين",
    "auth.passwordReq1": "8 أحرف على الأقل",
    "auth.passwordReq2": "تحتوي على رقم",
    "auth.passwordReq3": "تحتوي على حرف",
    "auth.backToSignIn": "العودة إلى تسجيل الدخول",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.demoAccounts": "حسابات تجريبية",
    "auth.demoPassword": "كلمة المرور لجميع الحسابات",
    "auth.demoAutoFill": "انقر على أي صف لملء النموذج تلقائياً",

    // ── Triage ────────────────────────────────────────────────────────────────
    "triage.IMMEDIATE": "فوري (أحمر)",
    "triage.DELAYED": "مؤجل (أصفر)",
    "triage.MINIMAL": "بسيط (أخضر)",
    "triage.EXPECTANT": "محتضر (أسود)",
    "triage.DECEASED": "متوفى",
    "triage.UNKNOWN": "غير معروف",
    "triage.category": "فئة الفرز",
    "triage.algorithm": "خوارزمية الفرز",
    "triage.SALT": "SALT",
    "triage.START": "START",
    "triage.JUMPSTART": "JumpSTART (أطفال)",
    "triage.registerCasualty": "تسجيل مصاب",
    "triage.startAssessment": "تسجيل وبدء فرز SALT",
    "triage.tagSerial": "رقم بطاقة الفرز",
    "triage.estimatedAge": "العمر التقديري",
    "triage.sex": "الجنس",
    "triage.sex.MALE": "ذكر",
    "triage.sex.FEMALE": "أنثى",
    "triage.sex.UNKNOWN": "غير معروف",
    "triage.nationality": "الجنسية",
    "triage.gps": "إحداثيات GPS",
    "triage.canWalk": "هل يستطيع المريض المشي إلى منطقة محددة؟",
    "triage.hasLifeThreat": "هل يعاني المريض من نزيف حاد أو انسداد مجرى الهواء؟",
    "triage.lsiPossible": "هل يمكن تطبيق تدخل منقذ للحياة؟",
    "triage.abnormalVitals": "هل معدل التنفس غير طبيعي أو النبض غائب أو المريض لا يستجيب للأوامر؟",
    "triage.confirmTriage": "تأكيد الفرز",
    "triage.reassess": "إعادة التقييم",
    "triage.noCasualties": "لا يوجد مصابون مسجلون",
    "triage.selectIncident": "اختر حادثاً لعرض لوحة الفرز",
    "triage.identityConfirmed": "تم التحقق من الهوية",

    // ── Incidents ─────────────────────────────────────────────────────────────
    "incident.create": "الإعلان عن حادث",
    "incident.declare": "الإعلان عن حادث جديد",
    "incident.name": "اسم الحادث (بالإنجليزية)",
    "incident.nameAr": "اسم الحادث (بالعربية)",
    "incident.type": "النوع",
    "incident.severity": "الخطورة",
    "incident.location": "وصف الموقع",
    "incident.estimatedCasualties": "العدد التقديري للضحايا",
    "incident.notes": "ملاحظات",
    "incident.activatedAt": "وقت التفعيل",
    "incident.closedAt": "وقت الإغلاق",
    "incident.status.ACTIVATED": "مفعّل",
    "incident.status.ESCALATED": "متصاعد",
    "incident.status.DEACTIVATED": "معطّل",
    "incident.status.CLOSED": "مغلق",
    "incident.severity.LOW": "منخفض",
    "incident.severity.MODERATE": "متوسط",
    "incident.severity.HIGH": "عالٍ",
    "incident.severity.CATASTROPHIC": "كارثي",
    "incident.type.MASS_CASUALTY": "إصابات جماعية",
    "incident.type.NATURAL_DISASTER": "كارثة طبيعية",
    "incident.type.HAZMAT": "مواد خطرة",
    "incident.type.TERRORISM": "إرهاب",
    "incident.type.PANDEMIC": "وباء",
    "incident.type.INFRASTRUCTURE": "فشل البنية التحتية",
    "incident.type.OTHER": "أخرى",
    "incident.noActive": "لا توجد حوادث نشطة",
    "incident.allIncidents": "جميع الحوادث",

    // ── Patient Tracking ──────────────────────────────────────────────────────
    "tracking.board": "لوحة تتبع المرضى",
    "tracking.provisionalId": "الرقم المؤقت",
    "tracking.addEvent": "إضافة حدث",
    "tracking.eventType": "نوع الحدث",
    "tracking.locationDesc": "وصف الموقع",
    "tracking.confirmIdentity": "تأكيد الهوية",
    "tracking.firstName": "الاسم الأول",
    "tracking.lastName": "اسم العائلة",
    "tracking.nationalId": "رقم الهوية الوطنية",
    "tracking.disposition": "الوضع الحالي",
    "tracking.disposition.AT_SCENE": "في موقع الحادث",
    "tracking.disposition.IN_TRANSPORT": "في النقل",
    "tracking.disposition.AT_FACILITY": "في المنشأة",
    "tracking.disposition.DISCHARGED": "خرج",
    "tracking.disposition.TRANSFERRED": "محوّل",
    "tracking.disposition.DECEASED": "متوفى",
    "tracking.noEvents": "لا توجد أحداث مسجلة",
    "tracking.noAssessments": "لا توجد تقييمات فرز",

    // ── OR Queue ──────────────────────────────────────────────────────────────
    "or.newCase": "حالة جراحية جديدة",
    "or.caseCode": "رمز الحالة",
    "or.procedureType": "نوع الإجراء الجراحي",
    "or.priority": "الأولوية (1-100)",
    "or.estimatedDuration": "المدة التقديرية (دقيقة)",
    "or.bloodType": "فصيلة الدم",
    "or.isDamageControl": "جراحة السيطرة على الضرر (DCS)",
    "or.mtpActivated": "بروتوكول نقل الدم الكثيف نشط",
    "or.rbcUnits": "وحدات كريات الدم الحمراء",
    "or.ffpUnits": "وحدات البلازما الطازجة",
    "or.platelets": "الصفائح الدموية",
    "or.transition": "تقدم الحالة",
    "or.activeInOR": "نشط في غرفة العمليات",
    "or.pendingOR": "في الانتظار",
    "or.completedOR": "مكتمل",
    "or.status.PROPOSED": "مقترح",
    "or.status.SCHEDULED": "مجدول",
    "or.status.IN_OR_PREP": "تحضير غرفة العمليات",
    "or.status.INDUCTION": "التخدير",
    "or.status.INCISION": "الشق الجراحي",
    "or.status.CLOSURE": "الإغلاق",
    "or.status.IN_PACU": "في غرفة الإفاقة",
    "or.status.OUT_PACU": "خارج غرفة الإفاقة",
    "or.status.COMPLETE": "مكتمل",
    "or.status.CANCELLED": "ملغى",
    "or.status.ABORTED": "موقوف",

    // ── Resources ─────────────────────────────────────────────────────────────
    "resources.title": "الموارد واللوجستيات",
    "resources.addResource": "إضافة مورد",
    "resources.resourceName": "اسم المورد",
    "resources.resourceType": "نوع المورد",
    "resources.totalCount": "الإجمالي",
    "resources.inUseCount": "قيد الاستخدام",
    "resources.availableCount": "متاح",
    "resources.maintenanceCount": "في الصيانة",
    "resources.lowThreshold": "حد التنبيه المنخفض",
    "resources.unit": "الوحدة",
    "resources.lowAlert": "منخفض",
    "resources.utilization": "نسبة الاستخدام",
    "resources.criticalCare": "الرعاية الحرجة",
    "resources.surgical": "الجراحة",
    "resources.bloodProducts": "منتجات الدم",
    "resources.ppe": "معدات الوقاية الشخصية",
    "resources.medications": "الأدوية",

    // ── Transport ─────────────────────────────────────────────────────────────
    "transport.title": "النقل",
    "transport.addTransport": "إضافة وسيلة نقل",
    "transport.transportCode": "رمز النقل",
    "transport.vehicleType": "نوع المركبة",
    "transport.driverName": "السائق / الطاقم",
    "transport.etaMinutes": "وقت الوصول المتوقع (دقيقة)",
    "transport.status.AVAILABLE": "متاح",
    "transport.status.DISPATCHED": "تم الإرسال",
    "transport.status.EN_ROUTE": "في الطريق",
    "transport.status.AT_SCENE": "في موقع الحادث",
    "transport.status.LOADED": "محمّل",
    "transport.status.RETURNING": "عائد",
    "transport.status.OUT_OF_SERVICE": "خارج الخدمة",
    "transport.noTransports": "لا توجد وسائل نقل مسجلة",

    // ── ICS Forms ─────────────────────────────────────────────────────────────
    "ics.title": "نماذج ICS",
    "ics.submitForm": "إرسال النموذج",
    "ics.acknowledge": "تأكيد الاستلام",
    "ics.status.DRAFT": "مسودة",
    "ics.status.SUBMITTED": "مُرسَل",
    "ics.status.ACKNOWLEDGED": "تم الاستلام",
    "ics.status.SUPERSEDED": "مستبدَل",
    "ics.HICS_201": "HICS 201 — إحاطة الحادث",
    "ics.HICS_202": "HICS 202 — أهداف الحادث",
    "ics.HICS_203": "HICS 203 — تعيينات التنظيم",
    "ics.HICS_204": "HICS 204 — قائمة المهام",
    "ics.HICS_205A": "HICS 205A — قائمة الاتصالات",
    "ics.HICS_213": "HICS 213 — رسالة عامة",
    "ics.HICS_214": "HICS 214 — سجل النشاط",
    "ics.HICS_254": "HICS 254 — تتبع المرضى",
    "ics.noForms": "لم يتم إرسال أي نماذج ICS",

    // ── Communications ────────────────────────────────────────────────────────
    "comms.title": "الاتصالات",
    "comms.sendMessage": "إرسال رسالة",
    "comms.channel": "القناة",
    "comms.messagePriority": "الأولوية",
    "comms.priority.ROUTINE": "عادي",
    "comms.priority.URGENT": "عاجل",
    "comms.priority.FLASH": "فلاش",
    "comms.channel.COMMAND": "القيادة",
    "comms.channel.OPERATIONS": "العمليات",
    "comms.channel.LOGISTICS": "اللوجستيات",
    "comms.channel.MEDICAL": "الطبي",
    "comms.channel.GENERAL": "عام",
    "comms.noMessages": "لا توجد رسائل في هذه القناة",
    "comms.acknowledged": "تم التأكيد",

    // ── EMT MDS ───────────────────────────────────────────────────────────────
    "emtMds.title": "تقارير WHO EMT MDS",
    "emtMds.newReport": "تقرير جديد",
    "emtMds.orgName": "اسم المنظمة",
    "emtMds.classification": "تصنيف الفريق الطبي",
    "emtMds.consultations": "إجمالي الاستشارات",
    "emtMds.admissions": "الحالات الجديدة",
    "emtMds.bedCapacity": "إجمالي طاقة الأسرة",
    "emtMds.traumaCases": "حالات الصدمات",
    "emtMds.surgicalProcedures": "الإجراءات الجراحية",
    "emtMds.deaths": "الوفيات",
    "emtMds.discharges": "الخروج",
    "emtMds.referrals": "الإحالات",
    "emtMds.constraints": "القيود التشغيلية",
    "emtMds.risks": "مخاطر المجتمع",
    "emtMds.status.DRAFT": "مسودة",
    "emtMds.status.SUBMITTED": "مُرسَل",
    "emtMds.status.APPROVED": "معتمد",
    "emtMds.noReports": "لا توجد تقارير EMT MDS",

    // ── AAR ───────────────────────────────────────────────────────────────────
    "aar.title": "مراجعة ما بعد الحادث",
    "aar.selectIncident": "اختر حادثاً للمراجعة",
    "aar.totalCasualties": "إجمالي الضحايا",
    "aar.deceased": "المتوفون",
    "aar.discharged": "الخارجون",
    "aar.mortalityRate": "معدل الوفيات",
    "aar.survivalRate": "معدل النجاة",
    "aar.orCompleted": "العمليات المكتملة",
    "aar.identityConfirmed": "تم التحقق من الهوية",
    "aar.duration": "مدة الحادث",
    "aar.ongoing": "جارٍ",
    "aar.kpis": "مؤشرات الأداء الرئيسية",
    "aar.selectPrompt": "اختر حادثاً لعرض مؤشرات الأداء",
    "aar.closedHint": "جرّب الحادث المغلق للحصول على مراجعة كاملة",

    // ── Admin Panel ───────────────────────────────────────────────────────────
    "admin.title": "لوحة الإدارة",
    "admin.users": "المستخدمون",
    "admin.invitations": "الدعوات",
    "admin.accessRequests": "طلبات الوصول",
    "admin.facilities": "المنشآت",
    "admin.auditLog": "سجل التدقيق",
    "admin.addUser": "إضافة مستخدم",
    "admin.editUser": "تعديل الملف الشخصي",
    "admin.deleteUser": "حذف المستخدم",
    "admin.deleteUserConfirm": "حذف المستخدم؟ لا يمكن التراجع عن هذا.",
    "admin.setPassword": "تعيين كلمة المرور",
    "admin.setPasswordFor": "تعيين كلمة مرور لـ",
    "admin.sendInvitation": "إرسال دعوة",
    "admin.createInvitation": "إنشاء دعوة",
    "admin.inviteEmail": "البريد الإلكتروني",
    "admin.inviteRole": "الدور المخصص",
    "admin.inviteMessage": "رسالة شخصية (اختياري)",
    "admin.inviteCreated": "تم إنشاء الدعوة!",
    "admin.inviteExpiry": "تنتهي في",
    "admin.inviteLink": "رابط الدعوة",
    "admin.invitedBy": "دعوة من",
    "admin.addFacility": "إضافة منشأة",
    "admin.facilityName": "الاسم (بالإنجليزية)",
    "admin.facilityNameAr": "الاسم (بالعربية)",
    "admin.facilityCode": "الرمز",
    "admin.facilityType": "النوع",
    "admin.facilityCity": "المدينة",
    "admin.facilityPhone": "الهاتف",
    "admin.totalBeds": "إجمالي الأسرة",
    "admin.icuBeds": "أسرة العناية المركزة",
    "admin.orRooms": "غرف العمليات",
    "admin.ventilators": "أجهزة التنفس الاصطناعي",
    "admin.fullName": "الاسم الكامل",
    "admin.email": "البريد الإلكتروني",
    "admin.jobTitle": "المسمى الوظيفي",
    "admin.phone": "الهاتف",
    "admin.role": "الدور",
    "admin.language": "اللغة",
    "admin.activeAccount": "حساب نشط",
    "admin.lastSignIn": "آخر تسجيل دخول",
    "admin.noUsers": "لا يوجد مستخدمون",
    "admin.noInvitations": "لم يتم إرسال أي دعوات بعد",
    "admin.noRequests": "لا توجد طلبات وصول بعد",
    "admin.searchUsers": "البحث عن مستخدمين...",
    "admin.requestFrom": "قدّم طلباً",
    "admin.sendInvite": "إرسال دعوة",
    "admin.reject": "رفض",
    "admin.invited": "تمت الدعوة",
    "admin.auditUser": "المستخدم",
    "admin.auditAction": "الإجراء",
    "admin.auditResource": "المورد",
    "admin.auditIp": "عنوان IP",
    "admin.noAuditLogs": "لا توجد سجلات تدقيق",

    // ── Dashboard ─────────────────────────────────────────────────────────────
    "dashboard.title": "لوحة قيادة القيادة",
    "dashboard.activeIncidents": "الحوادث النشطة",
    "dashboard.totalCasualties": "إجمالي الضحايا",
    "dashboard.immediate": "فوري (أحمر)",
    "dashboard.orActive": "عمليات جارية",
    "dashboard.orPending": "عمليات معلقة",
    "dashboard.quickNav": "التنقل السريع",
    "dashboard.noActiveIncidents": "لا توجد حوادث نشطة",

    // ── Roles ─────────────────────────────────────────────────────────────────
    "role.superadmin": "مدير النظام",
    "role.admin": "مدير",
    "role.incident_commander": "قائد الحادث",
    "role.clinician": "طبيب سريري",
    "role.triage_officer": "ضابط الفرز",
    "role.logistics": "اللوجستيات",
    "role.viewer": "مشاهد",

    // ── Public Portal ─────────────────────────────────────────────────────────
    "portal.title": "بوابة لمّ شمل الأسر",
    "portal.subtitle": "ابحث عن ذويك المصابين في الحوادث الكبرى.",
    "portal.search": "البحث برقم الهوية أو رقم بطاقة الفرز",
    "portal.privacyNotice": "هذه البوابة تعرض معلومات الحالة العامة فقط. لا تُشارك أي بيانات طبية شخصية.",
    "portal.noResults": "لم يتم العثور على تطابق. يرجى الاتصال بخدمات الطوارئ.",
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  dir: "ltr",
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem("mci_lang") as Lang) ?? "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("mci_lang", l);
  };

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
